spring:
  redis:
    host: 10.201.0.222
    port: 22221
    database: 0
  octopus:
    broker:
      group: group1
      id: broker1
      host: localhost
      port: 20000
      storage:
        retain: redis
        publish: redis
        subscription: redis