spring:
  application:
    name: ${spring.octopus.broker.group}-${spring.octopus.broker.id}
  aop:
    auto: true
  octopus:
    broker:
      group: GROUP1
      id: BROKER1
      host: localhost
      port: 20000
      storage:
        retain: redis
        publish: redis
        subscription: redis
        session: redis
      auth:
        enable: false
  redis:
    host: 10.201.0.222
    port: 22221
    database: 0
