spring:
  datasource:
    url: jdbc:mysql://10.201.0.222:22220/octopus
    username: root
    password: 111111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      url: redis://10.201.0.222:22221/0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    consul:
      host: 10.201.0.222
      port: 8500
octopus:
  broker:
    auth:
      enable: false
    id: BROKER_1
    host: localhost
    port: 20000
grpc:
  consul:
    discovery:
      register-health-check: true
      enabled: true
      tags:
        - "${octopus.broker.id}"
      instance-id: "${octopus.broker.id}"
      metadata:
        broker-id: "${octopus.broker.id}"
  port: 19999